version: '3'

services:
  app:
    build: .
    platform: linux/arm64/v8
    container_name: app
    hostname: app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=transactiondb

  mongo:
    image: 'arm64v8/mongo:4.0'
    platform: linux/arm64/v8
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"